name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Building and Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            clang \
            clang-tidy \
            clang-format \
            doxygen \
            graphviz \
            xorg-dev

      - name: Configure (CMake)
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Develop \
            -G "Unix Makefiles"

      - name: Build
        run: cmake --build build -- -j2

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Clang-Tidy check
        run: clang-tidy -p build include/ct9/*.h --config-file=.clang-tidy

      - name: Clang-Format check
        run: clang-format -n include/ct9/Trie.h

      - name: Generate documentation
        run: |
          doxygen --version
          doxygen Doxyfile

      - name: Commit generated documentation
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "Update documentation [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

